### ISSUE TITLE
QcWqSanity - add description of failure

### ISSUE THREAD

**Issue by wright13** [nationalparkservice/mojn-ds-rpackage#12]
It would be helpful to have a column in the function returned by QcWqSanity that describes the nature of the sanity check failure, e.g. "pH median >10"

**Comment by mojave-meow** [comment]
Worth changing sanity check to outlier check or just semantics?

**Comment by wright13** [comment]
> Worth changing sanity check to outlier check or just semantics?

I think it's ok as is, but I don't feel strongly. In my mind sanity check makes more sense because we're looking at specific thresholds instead of statistical outliers.
