### ISSUE TITLE
QcWqMedian and QcWqCleaned - NA rows

### ISSUE THREAD

**Issue by wright13** [nationalparkservice/mojn-ds-rpackage#13]
For visits where WQ was not collected, all WQ data shows up as NA. Do we want to filter these rows out? Or include a column (perhaps flow condition) to indicate that WQ was not collected?

**Comment by wright13** [comment]
Alternately we could provide a separate function that lists visit info and leave it to users to join those data if necessary...

**Comment by mojave-meow** [comment]
Filtered out visits where no water quality data were collected in WqMedian.
Filtered out NAs in qcWqLong.
