### ISSUE TITLE
QcWqCleaned - filter out CAMO data here?

### ISSUE THREAD

**Issue by wright13** [nationalparkservice/mojn-ds-rpackage#14]
Would it be worth removing CAMO data at this step instead of further down the line in analysis and plotting fxns?

**Comment by mojave-meow** [comment]
Still thinking about CAMO. Eventually, the two springs will be incorporated into the 3-year rotation at the same time as MOJA, so the data are intended to be available and used for future analysis, but the recon year is just clogging up the graphs right now until monitoring at the park is fully implemented.

**Comment by wright13** [comment]
> Still thinking about CAMO. Eventually, the two springs will be incorporated into the 3-year rotation at the same time as MOJA, so the data are intended to be available and used for future analysis, but the recon year is just clogging up the graphs right now until monitoring at the park is fully implemented.

So you're planning on including the recon data in the analysis dataset? In any case, if we're not using it now I think I'd still recommend filtering it out at the earliest step that makes sense - that way when we do start including it, we'll only have to modify a single function in the package. For transparency, I'd maybe add a warning that says CAMO is currently being excluded from analysis.

**Comment by mojave-meow** [comment]
Rethinking this, since CAMO isn't technically part of the DS protocol. I think the raw data we collect can be made available, but the park should be excluded from analysis and reporting for now. I will remove CAMO at the qcWqCleaned step.
